name: Release

on:
  push:
    branches:
      - 'release-test*'  # Only run on branches with release-test prefix

permissions:
  contents: read

jobs:
  # Use the reusable trusted tag workflow for releases if approved
  release:
    if: github.event.action != 'labeled' && needs.release-check.outputs.skip != 'true'
    permissions:
      id-token: write    # Required for SLSA provenance
      contents: write    # Required for release and tag creation
      pull-requests: write # Required for bumpr commenting
      actions: read      # Required for SLSA generator
      attestations: write # Required for build provenance attestation
    uses: actionutils/trusted-go-releaser/.github/workflows/trusted-release-workflow.yml@main
    with:
      environment: release
      setup-go: true
      setup-bun: true
      setup-zig: true
    secrets:
      goreleaser-env-json: |
        {
          "HOMEBREW_GITHUB_TOKEN": "${{ secrets.HOMEBREW_GITHUB_TOKEN }}"
        }
